services:
# backend
  db:
    image: mysql:8.0.32
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
      - ./mysql-data:/var/lib/mysql
    environment: 
      TZ: Asia/Bangkok
      MYSQL_DATABASE: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment: 
      TZ: Asia/Bangkok   
    networks:
      - mynetwork
# fontend
  php:
    build: 
        context: ./php/
        dockerfile: Dockerfile
    environment: 
      TZ: Asia/Bangkok
    restart: always
    ports:
     - 888:80
    volumes:
     - ./php/src:/var/www/html/
    networks:
      - mynetwork

  flutter-web:
    image: python:3.8-slim
    volumes:
      - ./flutter/web:/app
    working_dir: /app
    command: python -m http.server 80
    restart: always
    ports:
      - 8080:80
    networks:
      - mynetwork


networks:
  mynetwork:
